-- CREATING USER TABLE
CREATE TABLE IF NOT EXISTS T_USER_NATH(
USER_ID INT( 20 ) NOT NULL AUTO_INCREMENT ,
USER_LOGIN VARCHAR( 30 ) NOT NULL ,
USER_PASSWORD VARCHAR (15) NOT NULL,
USER_FIRST_NAME VARCHAR( 30 ) ,
USER_MIDDLE_NAME VARCHAR( 30 ) ,
USER_LAST_NAME VARCHAR( 30 ) ,
PRIMARY KEY ( USER_ID, USER_LOGIN )
)